### ISSUE TITLE
Custom Constraints (NOT) has no Effect

### ISSUE THREAD

**Issue by Siddiq200** [GoodDeeds/Timetabler#7]
`COURSE * INSTRUCTOR {T1} NOT IN SLOT {MO1,TU1} WEIGHT -1`

This line in custom constraints file should restrict T1's class in Slot MO1 and TU1 but it is assigning these slots to T1's course.

Please Help!

**Comment by GoodDeeds** [comment]
Could you please provide a complete example (however small it may be) where this fails (i.e., field input, inputs, and custom constraints)?

**Comment by Siddiq200** [comment]
->Fields
```
weights: # Assignment, high level
  instructor: [-1, -1]
  segment: [-1, -1]
  is_minor: [-1, -1]
  program: -1
  classroom: [-1, -1]
  slot: [-1, -1]

# Predefined Weights
# instructorSingleCourseAtATime
# classroomSingleCourseAtATime
# programSingleCoreCourseAtATime
# minorInMinorTime
# twoLectures of same 
# exactlyOneSlotPerCourse
# exactlyOneInstructorPerCourse
# exactlyOneSegmentPerCourse
# exactlyOneIsMinorPerCourse
# exactlyOneClassroomPerCourse
# coreInMorningTime
# programAtMostOneOfCoreOrElective

predefined_weights:
  - clause: 0
    weight: 1

segments:
  start: 1
  end: 2

instructors:
  - T1
  - T2
  - T3
  - T4
  - T5
  - T6
  - T7
  - T8
  - T9
  - T10

classrooms:
  - number: CS001
    size: 200
  - number: CS002
    size: 200
  - number: CS003
    size: 200
  - number: CS004
    size: 200
  - number: CS-Lab-001
    size: 250
  - number: CS-Lab-002
    size: 250

programs:
  - BSCS-S1-A
  - BSCS-S2-A

slots:
  - name: MO1
    is_minor: false
    time_periods:
      - day: Monday
        start: 8:01
        end: 9:30
  - name: MO2
    is_minor: false
    time_periods:
      - day: Monday
        start: 9:31
        end: 11:00
  - name: MO_LAB_1
    is_minor: lab
    time_periods:
      - day: Monday
        start: 8:01
        end: 10:00
  - name: MO_LAB_2
    is_minor: lab
    time_periods:
      - day: Monday
        start: 10:01
        end: 12:00
  - name: MO_MI_1
    is_minor: true
    time_periods:
      - day: Monday
        start: 8:01
        end: 9:00
  - name: MO_MI_2
    is_minor: true
    time_periods:
      - day: Monday
        start: 9:01
        end: 10:00
  - name: TU1
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 8:00
        end: 9:30
  - name: TU2
    is_minor: false
    time_periods:
      - day: Tuesday
        start: 9:31
        end: 10:59
  - name: TU_MI_1
    is_minor: true
    time_periods:
      - day: Tuesday
        start: 8:01
        end: 9:00
  - name: TU_MI_2
    is_minor: true
    time_periods:
      - day: Tuesday
        start: 9:01
        end: 10:00
  - name: WE1
    is_minor: false
    time_periods:
      - day: Wednesday
        start: 8:00
        end: 9:29
  - name: WE2
    is_minor: false
    time_periods:
      - day: Wednesday
        start: 9:31
        end: 10:59
  - name: WE_LAB_1
    is_minor: lab
    time_periods:
      - day: Wednesday
        start: 8:01
        end: 10:00
  - name: TH1
    is_minor: false
    time_periods:
      - day: Thursday
        start: 8:00
        end: 9:29
  - name: TH2
    is_minor: false
    time_periods:
      - day: Thursday
        start: 9:31
        end: 10:59
  - name: FR1
    is_minor: false
    time_periods:
      - day: Friday
        start: 8:00
        end: 9:29
  - name: FR2
    is_minor: false
    time_periods:
      - day: Friday
        start: 9:31
        end: 10:59

```
->Input
```
name | class_size | instructor | segment | is_minor | BSCS-S1-A | BSCS-S2-A | classroom | slot
-- | -- | -- | -- | -- | -- | -- | -- | --
CS3550 | 40 | T1 | 12 | No | Core | No |   |  
CS6250 | 40 | T2 | 12 | No | Core | No |   |  
CS5470 | 10 | T3 | 12 | No | Core | No |   |  
CS3550 | 40 | T1 | 12 | No | Core | No |   |  
CS6250 | 40 | T2 | 12 | No | Core | No |   |  
CS5470 | 10 | T3 | 12 | No | Core | No |   |  

```

->Output

```
name | class_size | instructor | segment | is_minor | BSCS-S1-A | BSCS-S2-A | classroom | slot
-- | -- | -- | -- | -- | -- | -- | -- | --
CS3550 | 40 | T1 | 12 | No | Core | No | CS001 | TU1
CS6250 | 40 | T2 | 12 | No | Core | No | CS001 | TH2
CS5470 | 10 | T3 | 12 | No | Core | No | CS001 | WE1
CS3550 | 40 | T1 | 12 | No | Core | No | CS001 | MO1
CS6250 | 40 | T2 | 12 | No | Core | No | CS001 | TU2
CS5470 | 10 | T3 | 12 | No | Core | No | CS001 | MO2
```


->Custom
`COURSE * INSTRUCTOR {T1} NOT IN SLOT {MO1,TU1} WEIGHT -1`
